### ISSUE TITLE
Repository suggestion

### ISSUE THREAD

**Issue by louis030195** [rom1504/ideas#2]
What do you think of this:
1. Find another name ([meme](https://en.wikipedia.org/wiki/Meme) ?)
2. make this repository use github page (and automate github page when pushing on master using github actions)
3. All PRs including A SINGLE IDEA have to be reviewed (by most people possible) with critical arguments, then can be merged when all approve (idea is interesting or not, well explained, references, etc.)
4. Some idea could have a bit of js etc for animating (i think its possible with github page?)

Why ?
* ideas are [meme](https://en.wikipedia.org/wiki/Meme), they follow the rule of evolution, PR allow trial and error, feedback, improvement ... Ideas ends-up much better when going through evolution

**Comment by rom1504** [comment]
I think that's a nice project idea, go ahead and do it :)
I think I'm going to keep this particular repo about my idea (or idea I found), and kind of low effort, I'm putting stuff here when I feel like it, and at some point it might reach a critical mass when it makes sense to do something more with it.
